### PR TITLE
Fixing compilation with ghc-9.0-rc1

### LINKED ISSUE #34: Doesn't build with GHC-9.0
The `modern-uri` library doesn't build with `ghc-9.0-rc1`. When trying to build with the new compiler, the following compilation errors occur:

```
Text/URI/Types.hs:126:10: error:
    • Couldn't match type ‘m’ with ‘TH.Q’
      Expected: URI -> m TH.Exp
        Actual: URI -> TH.Q TH.Exp
      ‘m’ is a rigid type variable bound by
        the type signature for:
          TH.lift :: forall (m :: * -> *). TH.Quote m => URI -> m TH.Exp
        at Text/URI/Types.hs:126:3-6
    • In the expression: liftData
      In an equation for ‘TH.lift’: TH.lift = liftData
      In the instance declaration for ‘TH.Lift URI’
    • Relevant bindings include
        lift :: URI -> m TH.Exp (bound at Text/URI/Types.hs:126:3)
    |
126 |   lift = liftData
    |          ^^^^^^^^

Text/URI/Types.hs:129:15: error:
    • Couldn't match type ‘TH.TExp a0’ with ‘URI’
      Expected: URI -> TH.Code m URI
        Actual: URI -> TH.Code m (TH.TExp a0)
    • In the expression: TH.unsafeTExpCoerce . TH.lift
      In an equation for ‘TH.liftTyped’:
          TH.liftTyped = TH.unsafeTExpCoerce . TH.lift
      In the instance declaration for ‘TH.Lift URI’
    |
129 |   liftTyped = TH.unsafeTExpCoerce . TH.lift
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Text/URI/Types.hs:169:10: error:
    • Couldn't match type ‘m’ with ‘TH.Q’
      Expected: Authority -> m TH.Exp
        Actual: Authority -> TH.Q TH.Exp
      ‘m’ is a rigid type variable bound by
        the type signature for:
          TH.lift :: forall (m :: * -> *).
                     TH.Quote m =>
                     Authority -> m TH.Exp
        at Text/URI/Types.hs:169:3-6
    • In the expression: liftData
      In an equation for ‘TH.lift’: TH.lift = liftData
      In the instance declaration for ‘TH.Lift Authority’
    • Relevant bindings include
        lift :: Authority -> m TH.Exp (bound at Text/URI/Types.hs:169:3)
    |
169 |   lift = liftData
    |          ^^^^^^^^

Text/URI/Types.hs:172:15: error:
    • Couldn't match type ‘TH.TExp a1’ with ‘Authority’
      Expected: Authority -> TH.Code m Authority
        Actual: Authority -> TH.Code m (TH.TExp a1)
    • In the expression: TH.unsafeTExpCoerce . TH.lift
      In an equation for ‘TH.liftTyped’:
          TH.liftTyped = TH.unsafeTExpCoerce . TH.lift
      In the instance declaration for ‘TH.Lift Authority’
    |
172 |   liftTyped = TH.unsafeTExpCoerce . TH.lift
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Text/URI/Types.hs:195:10: error:
    • Couldn't match type ‘m’ with ‘TH.Q’
      Expected: UserInfo -> m TH.Exp
        Actual: UserInfo -> TH.Q TH.Exp
      ‘m’ is a rigid type variable bound by
        the type signature for:
          TH.lift :: forall (m :: * -> *). TH.Quote m => UserInfo -> m TH.Exp
        at Text/URI/Types.hs:195:3-6
    • In the expression: liftData
      In an equation for ‘TH.lift’: TH.lift = liftData
      In the instance declaration for ‘TH.Lift UserInfo’
    • Relevant bindings include
        lift :: UserInfo -> m TH.Exp (bound at Text/URI/Types.hs:195:3)
    |
195 |   lift = liftData
    |          ^^^^^^^^

Text/URI/Types.hs:198:15: error:
    • Couldn't match type ‘TH.TExp a2’ with ‘UserInfo’
      Expected: UserInfo -> TH.Code m UserInfo
        Actual: UserInfo -> TH.Code m (TH.TExp a2)
    • In the expression: TH.unsafeTExpCoerce . TH.lift
      In an equation for ‘TH.liftTyped’:
          TH.liftTyped = TH.unsafeTExpCoerce . TH.lift
      In the instance declaration for ‘TH.Lift UserInfo’
    |
198 |   liftTyped = TH.unsafeTExpCoerce . TH.lift
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Text/URI/Types.hs:221:10: error:
    • Couldn't match type ‘m’ with ‘TH.Q’
      Expected: QueryParam -> m TH.Exp
        Actual: QueryParam -> TH.Q TH.Exp
      ‘m’ is a rigid type variable bound by
        the type signature for:
          TH.lift :: forall (m :: * -> *).
                     TH.Quote m =>
                     QueryParam -> m TH.Exp
        at Text/URI/Types.hs:221:3-6
    • In the expression: liftData
      In an equation for ‘TH.lift’: TH.lift = liftData
      In the instance declaration for ‘TH.Lift QueryParam’
    • Relevant bindings include
        lift :: QueryParam -> m TH.Exp (bound at Text/URI/Types.hs:221:3)
    |
221 |   lift = liftData
    |          ^^^^^^^^

Text/URI/Types.hs:224:15: error:
    • Couldn't match type ‘TH.TExp a3’ with ‘QueryParam’
      Expected: QueryParam -> TH.Code m QueryParam
        Actual: QueryParam -> TH.Code m (TH.TExp a3)
    • In the expression: TH.unsafeTExpCoerce . TH.lift
      In an equation for ‘TH.liftTyped’:
          TH.liftTyped = TH.unsafeTExpCoerce . TH.lift
      In the instance declaration for ‘TH.Lift QueryParam’
    |
224 |   liftTyped = TH.unsafeTExpCoerce . TH.lift
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Text/URI/Types.hs:267:10: error:
    • Couldn't match type ‘m’ with ‘TH.Q’
      Expected: RText l -> m TH.Exp
        Actual: RText l -> TH.Q TH.Exp
      ‘m’ is a rigid type variable bound by
        the type signature for:
          TH.lift :: forall (m :: * -> *). TH.Quote m => RText l -> m TH.Exp
        at Text/URI/Types.hs:267:3-6
    • In the expression: liftData
      In an equation for ‘TH.lift’: TH.lift = liftData
      In the instance declaration for ‘TH.Lift (RText l)’
    • Relevant bindings include
        lift :: RText l -> m TH.Exp (bound at Text/URI/Types.hs:267:3)
    |
267 |   lift = liftData
    |          ^^^^^^^^

Text/URI/Types.hs:270:15: error:
    • Couldn't match type: TH.TExp a4
                     with: RText l
      Expected: RText l -> TH.Code m (RText l)
        Actual: RText l -> TH.Code m (TH.TExp a4)
    • In the expression: TH.unsafeTExpCoerce . TH.lift
      In an equation for ‘TH.liftTyped’:
          TH.liftTyped = TH.unsafeTExpCoerce . TH.lift
      In the instance declaration for ‘TH.Lift (RText l)’
    • Relevant bindings include
        liftTyped :: RText l -> TH.Code m (RText l)
          (bound at Text/URI/Types.hs:270:3)
    |
270 |   liftTyped = TH.unsafeTExpCoerce . TH.lift
    |
```

### PR DESCRIPTION
**Pull request by recursion-ninja**
Fixes #34 .

### CODE REVIEW

**Comment by mrkkrp** [comment]
I'm going to keep this in pending state till 9.0 is officially released.

**Comment by mithrandi** [comment]
Ping! :smile:

**Comment by sjakobi** [comment]
Ping @mrkkrp! :)

**Comment by sjakobi** [comment]
Also, @recursion-ninja, please note the merge conflict.

**Comment by recursion-ninja** [comment]
@sjakobi The CI build logs have expired, so I'm not aware what the "merge conflict" (CI issue?) was. I have a fleeting recollection from many months past that it was not related to the code changes, but a spurious tooling issue. Perhaps @mrkkrp could restart the CI so we can identify and address any potential issues.

**Comment by sjakobi** [comment]
@recursion-ninja Thanks for the quick response. I was simply referring to GitHub listing `modern-uri.cabal` as a "conflicting file". A rebase should help.

**Comment by recursion-ninja** [comment]
@sjakobi, Ah I see. I didn't read the merge status closely enough.

**Comment by mrkkrp** [comment]
Hey @sjakobi and @recursion-ninja I'm not sure the ecosystem is ready for 9.0. Last time I tried there were dependencies that wouldn't build even for simpler packages like `megaparsec`, notoriously `criterion`'s dependencies had problems. I do not know if the situation has changed. If it has, I'll go through all my packages to make sure they work, if not, I'll wait more.

**Comment by sjakobi** [comment]
Yeah, https://github.com/haskell-hvr/cassava/issues/191 is still a blocker for the benchmarks. Since users mostly rely on the library component, I think you could still make a compatible release.

Or you could consider switching to `tasty-bench` for the benchmarks…

**Comment by recursion-ninja** [comment]
@mrkkrp , @sjakobi While I agree that the Haskell ecosystem isn't holistically prepared for `ghc-9.0.*` (despite having a release candidate available for 6 months prior to release), I do think it's important for each package to push for compatibility as soon as possible, lest the ecosystem stagnate.

The following `cabal` invocation successfully builds, leading me to believe (perhaps wrongly) that this patch is future proofed for when the dependencies are updated to be compatible with `ghc-9.0.*`
```
cabal build --enable-benchmarks --enable-tests --with-compiler=ghc-9.0.1 --allow-newer=base,template-haskell
```

**Comment by recursion-ninja** [comment]
@mrkkrp , @sjakobi this PR looks *mostly* good to me. 

I didn't add GHC-9.0.1 to the CI build matrix in this PR as it's not supported via GitHub actions yet. I was told that GHC-8.10.4, GHC-9.0.1, and Cabal-3.4.0.0 should be added to GitHub actions by the end of next week. It may be worth delaying merging the PR until next week to see if we can wrap in the expanded CI builds in the same commit.

**Comment by sjakobi** [comment]
> Yeah, [haskell-hvr/cassava#191](https://github.com/haskell-hvr/cassava/issues/191) is still a blocker for the benchmarks.

`cassava` was made compatible with a Hackage revision. The benchmarks build fine now.

**Comment by recursion-ninja** [comment]
@mrkkrp I updated the CI as described above. I feel this is ready to merge.

**Comment by mrkkrp** [comment]
Will merge as soon as I get to it, it is in my immediate TODO list.

**Comment by mrkkrp** [comment]
Released 0.3.4.1.
